name: flutter_package
description: Este é um exemplo usando a api do pub.dev onde o objectivo é listar os pacotes
author: Edvaldo Martins <edvaldonuniomartins@gmail.com>
homepage: https://github.com/EdvaldoMartins/flutter_package_pub_dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #ui
  cupertino_icons: ^0.1.3
  flutter_markdown: ^0.6.2
  flutter_svg: ^0.22.0
  html: ^0.14.0+2
  pull_to_refresh: ^2.0.0
  customized:
    git:
      url: https://github.com/EdvaldoMartins/customized

  #state
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0

  #data class
  freezed_annotation: ^0.14.1
  freezed: ^0.14.1+3
  equatable: ^2.0.2

  #network
  dio: ^4.0.0
  http: ^0.13.0
  url_launcher: ^6.0.0-nullsafety
  data_connection_checker: ^0.3.4

  # Dependency Injection
  get_it: ^7.1.2

  #utils
  fluttertoast: ^7.1.5
  share: ^2.0.4
  dartz: ^0.10.0-nullsafety.1
  intl: ^0.17.0

  # Testing
  mockito: ^5.0.10



dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.1
  json_serializable: ^4.1.1
  build_resolvers: ^2.0.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Font
    - fonts:
        - asset: fonts/light.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/locale/
    - assets/icons/
    - assets/images/


#    flutter packages pub run build_runner build --delete-conflicting-outputs

